---
title: "Participantes"
toc: true
page-layout: article
---

## Coordinación

-   **Ana Ruth Escoto Castillo** — Facultad de Ciencias Políticas y Sociales, UNAM

------------------------------------------------------------------------

## Académicas y académicos UNAM

-   **Enrique Mauricio Padrón Innamorato** — Instituto de Investigaciones Jurídicas, UNAM\
-   **Gerardo Damián Hernández** — Centro Regional de Investigaciones Multidisciplinarias, UNAM\
-   **Isalia Nava Bolaños** — Instituto de Investigaciones Económicas, UNAM\
-   **Mercedes Pedrero y Nieto** — Centro Regional de Investigaciones Multidisciplinarias, UNAM

------------------------------------------------------------------------

## Académicas y académicos externos

-   **Emma Liliana Navarrete López** — El Colegio Mexiquense\
-   **María Edith Pacheco Gómez Muñoz** — El Colegio de México\
-   **María Viridiana Sosa Márquez** — Universidad Autónoma del Estado de México\
-   **Nelson Florez Vaquiro** — Facultad Latinoamericana de Ciencias Sociales (FLACSO)\
-   **Rosario Aparicio** — El Colegio de México\
-   **Rosa Patricia Román Reyes** — Universidad Autónoma del Estado de México

------------------------------------------------------------------------

## Investigadores posdoctorales

-   **Alfonso Ruiz Núñez** — Instituto de Investigaciones Sociales, UNAM\
-   **Jorge Rubén Afarian** — Instituto de Investigaciones Jurídicas, UNAM\
-   **Nina Castro Méndez** — Instituto de Investigaciones Jurídicas, UNAM

------------------------------------------------------------------------

## Alumnado UNAM

-   **Alma Delfina Ojeda Santiago** — Facultad de Derecho, UNAM\
-   **Eugenia López Cruz** — Facultad de Ciencias Políticas y Sociales, UNAM\
-   **Gabriela Corral Violante** — Facultad de Ciencias Políticas y Sociales, UNAM\
-   **Gonzalo Esteban Negreros Amaya** — Instituto de Investigaciones Económicas, UNAM\
-   **Litzy Jhoana Terrazas Guevara** — Facultad de Estudios Superiores Acatlán, UNAM\
-   **Óscar Uriel Valdés Bautista** — Facultad de Ciencias Políticas y Sociales, UNAM\
-   **Rubén Ramírez Martínez** — Facultad de Ciencias, UNAM\
-   **Zyanya Itzel Puga Sánchez** — Facultad de Ciencias Políticas y Sociales, UNAM

------------------------------------------------------------------------

## Alumnado externo

-   **Gabriela Alicia Cervantes Romo** — El Colegio de México

------------------------------------------------------------------------

## Contacto

📧 [papiit.in305925\@gmail.com](mailto:papiit.in305925@gmail.com)
